# [Advanced Numpy](https://medium.com/towards-data-science/advanced-numpy-master-stride-tricks-with-25-illustrated-exercises-923a9393ab20#a323)

In [1]:
import numpy as np
from numpy.lib.stride_tricks import as_strided

## Exercise 1

In [2]:
e = np.arange(1, 26, dtype=np.int8).reshape(5, 5)
a = as_strided(e, shape=(3,), strides=(e.itemsize * 1,))
assert np.array_equal(a, e[0, :3])
a

array([1, 2, 3], dtype=int8)

## Exercise 2

In [3]:
e = np.arange(1, 26, dtype=np.int8).reshape(5, 5)
a = as_strided(e, shape=(8,), strides=(e.itemsize * 1,))
a

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int8)

## Exercise 3

In [4]:
e = np.arange(1, 26, dtype=np.int16).reshape(5, 5)
a = as_strided(e, shape=(e.size,), strides=(e.itemsize * 1,))
assert np.array_equal(a, e.ravel())
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25], dtype=int16)

## Exercise 4

In [5]:
e = np.arange(1, 26, dtype=np.int8).reshape(5, 5)
a = as_strided(e, shape=(3,), strides=(e.itemsize * 2,))
assert np.array_equal(a, e[0, ::2])
a

array([1, 3, 5], dtype=int8)

## Exercise 5

In [6]:
e = np.arange(1, 26, dtype=np.int64).reshape(5, 5)
a = as_strided(e, shape=(4,), strides=(e.itemsize * e.shape[1],))
assert np.array_equal(a, e[:4, 0])
a

array([ 1,  6, 11, 16])

## Exercise 6

In [7]:
e = np.arange(1, 26, dtype=np.int64).reshape(5, 5)
a = as_strided(e, shape=(e.shape[0],), strides=(e.itemsize * (e.shape[1] + 1),))
assert np.array_equal(a, e.diagonal())
a

array([ 1,  7, 13, 19, 25])

## Exercise 7

In [8]:
e = np.arange(1, 26, dtype=np.int64).reshape(5, 5)
a = as_strided(e, shape=(5,), strides=(0,))
assert np.array_equal(a, np.broadcast_to(e[0, 0], (5,)))
a

array([1, 1, 1, 1, 1])

## Exercise 8

In [9]:
e = np.arange(1, 26, dtype=np.int64).reshape(5, 5)
a = as_strided(e, shape=(3, 4), strides=(e.itemsize * e.shape[1], e.itemsize * 1))
assert np.array_equal(a, e[0:3, :4])
a

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

## Exercise 9

In [10]:
e = np.arange(1, 26, dtype=np.int64).reshape(5, 5)
a = as_strided(e, shape=(4, 2), strides=(e.itemsize * (e.shape[1] + 1), e.itemsize * 1))
a

array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20]])

## Exercise 10

In [11]:
e = np.arange(1, 26, dtype=np.int64).reshape(5, 5)
a = as_strided(e, shape=(3, 3), strides=(e.itemsize * e.shape[1] * 2, e.itemsize * 2))
assert np.array_equal(a, e[::2, ::2])
a

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]])

## Exercise 11

In [12]:
e = np.arange(1, 26, dtype=np.int8).reshape(5, 5)
a = as_strided(e, shape=(3, 3), strides=(e.itemsize * 1, e.itemsize * e.shape[1]))
assert np.array_equal(a, e[:3, :3].T)
a

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13]], dtype=int8)

## Exercise 12

In [13]:
e = np.arange(1, 26, dtype=np.int32).reshape(5, 5)
a = as_strided(e, shape=(e.shape[0], 4), strides=(e.itemsize * e.shape[1], 0))
assert np.array_equal(a, np.broadcast_to(e[:, 0, None], (5, 4)))
a

array([[ 1,  1,  1,  1],
       [ 6,  6,  6,  6],
       [11, 11, 11, 11],
       [16, 16, 16, 16],
       [21, 21, 21, 21]], dtype=int32)

## Exercise 13

In [14]:
e = np.arange(1, 13, dtype=np.int32)
a = as_strided(e, shape=(4, 3), strides=(e.itemsize * 3, e.itemsize * 1))
assert np.array_equal(a, e.reshape(4, 3))
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)

## Exercise 14

In [15]:
e = np.arange(1, 11, dtype=np.int8)
a = as_strided(e, shape=(8, 3), strides=(e.itemsize * 1, e.itemsize * 1))
a

array([[ 1,  2,  3],
       [ 2,  3,  4],
       [ 3,  4,  5],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10]], dtype=int8)

## Exercise 15

In [16]:
e = np.asarray([0, 1, 10, 11, 20, 21, 30, 31, 40, 41, 50, 51], dtype=np.int8).reshape(
    6, 2
)
a = as_strided(e, shape=(4, 6), strides=(e.itemsize * e.shape[1], e.itemsize * 1))
a

array([[ 0,  1, 10, 11, 20, 21],
       [10, 11, 20, 21, 30, 31],
       [20, 21, 30, 31, 40, 41],
       [30, 31, 40, 41, 50, 51]], dtype=int8)

## Exercise 16

In [17]:
e = np.arange(1, 13, dtype=np.int8).reshape(3, 2, 2)
a = as_strided(e, shape=(3, 4), strides=(e.itemsize * 4, e.itemsize * 1))
assert np.array_equal(a, e.reshape(3, 4))
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int8)

## Exercise 17

In [18]:
e = np.arange(1, 26, dtype=np.int16).reshape(5, 5)
a = as_strided(
    e, shape=(2, 2, 2), strides=(e.itemsize * 5 * 3, e.itemsize * 5, e.itemsize * 1)
)
a

array([[[ 1,  2],
        [ 6,  7]],

       [[16, 17],
        [21, 22]]], dtype=int16)

## Exercise 18

In [19]:
e = np.arange(1, 26, dtype=np.int8).reshape(5, 5)
a = as_strided(
    e,
    shape=(2, 2, 3),
    strides=(e.itemsize * e.shape[1] * 2, e.itemsize * (e.shape[1] + 1), e.itemsize * 1),
)
a

array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [17, 18, 19]]], dtype=int8)

## Exercise 19

In [20]:
e = np.arange(1, 26, dtype=np.int16).reshape(5, 5)
a = as_strided(e, shape=(3, 2, 4), strides=(0, e.itemsize * e.shape[1], e.itemsize * 1))
assert np.array_equal(a, np.broadcast_to(e[0:2, 0:-1], (3, 2, 4)))
a

array([[[1, 2, 3, 4],
        [6, 7, 8, 9]],

       [[1, 2, 3, 4],
        [6, 7, 8, 9]],

       [[1, 2, 3, 4],
        [6, 7, 8, 9]]], dtype=int16)

## Exercise 20

In [21]:
e = np.arange(1, 13, dtype=np.int32).reshape(3, 2, 2)
a = as_strided(
    e,
    shape=(3, 2, 2),
    strides=(
        e.itemsize * e.shape[1] * e.shape[2],
        e.itemsize * 1,
        e.itemsize * e.shape[1],
    ),
)
assert np.array_equal(a, np.swapaxes(e, 1, 2))
a

array([[[ 1,  3],
        [ 2,  4]],

       [[ 5,  7],
        [ 6,  8]],

       [[ 9, 11],
        [10, 12]]], dtype=int32)

## Exercise 21

In [22]:
e = np.arange(1, 21, dtype=np.int64).reshape(4, 5)
a = as_strided(
    e,
    shape=(3, 2, 5),
    strides=(e.itemsize * e.shape[1], e.itemsize * e.shape[1], e.itemsize * 1),
)
a

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

## Exercise 22

In [23]:
e = np.arange(1, 13, dtype=np.int8)
a = as_strided(
    e, shape=(2, 2, 3), strides=(e.itemsize * 3 * 2, e.itemsize * 3, e.itemsize * 1)
)
assert np.array_equal(a, e.reshape(2, 2, 3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int8)

## Exercise 23

In [24]:
e = np.arange(1, 26, dtype=np.int8).reshape(5, 5)
a = as_strided(
    e,
    shape=(2, 2, 3, 3),
    strides=(
        e.itemsize * e.shape[1] * 2,
        e.itemsize * 2,
        e.itemsize * e.shape[1],
        e.itemsize * 1,
    ),
)
a

array([[[[ 1,  2,  3],
         [ 6,  7,  8],
         [11, 12, 13]],

        [[ 3,  4,  5],
         [ 8,  9, 10],
         [13, 14, 15]]],


       [[[11, 12, 13],
         [16, 17, 18],
         [21, 22, 23]],

        [[13, 14, 15],
         [18, 19, 20],
         [23, 24, 25]]]], dtype=int8)

## Exercise 24

In [25]:
e = np.arange(1, 13, dtype=np.int64).reshape(2, 2, 3)
a = as_strided(
    e,
    shape=(2, 2, 2, 3),
    strides=(e.itemsize * e.shape[2] * 2, 0, e.itemsize * e.shape[2], e.itemsize * 1),
)
assert np.array_equal(a, np.broadcast_to(e, (2, 2, 2, 3)).swapaxes(0, 1))
a

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 1,  2,  3],
         [ 4,  5,  6]]],


       [[[ 7,  8,  9],
         [10, 11, 12]],

        [[ 7,  8,  9],
         [10, 11, 12]]]])

## Exercise 25

In [26]:
e = np.arange(1, 17, dtype=np.int64)
a = as_strided(
    e,
    shape=(2, 2, 2, 2),
    strides=(e.itemsize * 4 * 2, e.itemsize * 4, e.itemsize * 2, e.itemsize * 1),
)
assert np.array_equal(a, e.reshape(2, 2, 2, 2))
a

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])